import type { Artwork } from "@/lib/types";

export const demoArtworks: Artwork[] = [
  {
    id: "demo-1",
    title: "Senja di Prambanan",
    artist: "Murni Rahayu",
    category: "landscape",
    status: "available",
    medium: "Oil on Canvas",
    year: 2024,
    price: 4500000,
    width_cm: 90,
    height_cm: 70,
    depth_cm: 3.5,
    weight_kg: null,
    description: "Keagungan Prambanan saat matahari terbenam, dengan cahaya keemasan dan langit ungu kemerahan.",
    image_url: null,
    colors: ["#C4722A", "#8B4E2E", "#F5A65B", "#1A1A2E", "#E8975A"],
    tags: ["landscape", "oil", "2024"],
    is_featured: true
  },
  {
    id: "demo-2",
    title: "Rindu yang Membara",
    artist: "Murni Rahayu",
    category: "abstrak",
    status: "auction",
    medium: "Acrylic on Canvas",
    year: 2024,
    price: 3200000,
    width_cm: 80,
    height_cm: 80,
    depth_cm: 4,
    weight_kg: null,
    description: "Ekspresi rindu lewat guratan merah dan oranye yang dinamis.",
    image_url: null,
    colors: ["#8B2E2E", "#D4521A", "#F08030", "#2C1810", "#C44A2A"],
    tags: ["abstrak", "acrylic", "2024"],
    is_featured: true
  },
  {
    id: "demo-3",
    title: "Perempuan dan Hujan",
    artist: "Murni Rahayu",
    category: "figuratif",
    status: "available",
    medium: "Mixed Media",
    year: 2023,
    price: 6800000,
    width_cm: 100,
    height_cm: 120,
    depth_cm: 3,
    weight_kg: null,
    description: "Figur perempuan dalam hujan sebagai simbol ketabahan dan ketenangan jiwa.",
    image_url: null,
    colors: ["#3A4A5C", "#6A8A9C", "#C4A882", "#2C3040", "#8AAAB8"],
    tags: ["figuratif", "mixed media", "2023"],
    is_featured: false
  },
  {
    id: "demo-4",
    title: "Gadis Batik",
    artist: "Murni Rahayu",
    category: "figuratif",
    status: "available",
    medium: "Oil on Canvas",
    year: 2025,
    price: 5500000,
    width_cm: 70,
    height_cm: 100,
    depth_cm: 3,
    weight_kg: null,
    description: "Potret gadis muda dengan batik kawung, lembut dan penuh detail.",
    image_url: null,
    colors: ["#1A1010", "#4A3020", "#8A6040", "#C49870", "#D4B888"],
    tags: ["figuratif", "oil", "2025"],
    is_featured: true
  }
];

